### ISSUE TITLE
make failure on ubuntu 14.06

### ISSUE THREAD

**Issue by RobinHankin** [bcrowell/general_relativity#1]
Hello, first of all a big Thank You for making this excellent resource available.

And while I'm writing, my make is giving me an error:

 
    OK~/Downloads/general_relativity-master make
    make[1]: Entering directory '/home/rhankin/Downloads/general_relativity-master'
    make[1]: Leaving directory '/home/rhankin/Downloads/general_relativity-master'
    perl -Iscripts scripts/run_eruby.pl
    run_eruby.pl, no_write=0, wiki=0, xhtml=0
    sh: 1: fruby: not found
    died on ch01/ch01.rbtex, 32512, cmd=BOOK_OUTPUT_FORMAT='print' DIR='ch01' fruby  
    ch01/ch01temp.postm4 >ch01/ch01temp.tex at scripts/run_eruby.pl line 147.
    Makefile:24: recipe for target 'default' failed
    make: *** [default] Error 127
    OK~/Downloads/general_relativity-master

**Comment by bcrowell** [comment]
Thanks for the report, but I cloned the project and built the book successfully, can't reproduce this error on my system. The script fruby is in the repo like it should be. You could check that it's executable and that the required version of ruby is installed (see README).

**Comment by RobinHankin** [comment]
thanks for this.  I have ruby installed, version 2.3.1, and fruby is  there and executable:

    OK~/Downloads/general_relativity-master ruby --version
    ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
    OK~/Downloads/general_relativity-master ./fruby
    fruby: Usage: fruby infile >outfile

but still get the same error:

    OK~/Downloads/general_relativity-master make
    make[1]: Entering directory '/home/rhankin/Downloads/general_relativity-master'
    make[1]: Leaving directory '/home/rhankin/Downloads/general_relativity-master'
    perl -Iscripts scripts/run_eruby.pl
    run_eruby.pl, no_write=0, wiki=0, xhtml=0
    sh: 1: fruby: not found
    died on ch01/ch01.rbtex, 32512, cmd=BOOK_OUTPUT_FORMAT='print' DIR='ch01' fruby ch01/ch01temp.postm4 >ch01/ch01temp.tex at scripts/run_eruby.pl line 147. Makefile:24: recipe for target 'default' failed
    make: *** [default] Error 127


Can you advise?

**Comment by igiann** [comment]
I have the same error when try to make

make[1]: Entering directory '/home/igiann/Documents/general_relativity'
make[1]: Leaving directory '/home/igiann/Documents/general_relativity'
perl -Iscripts scripts/run_eruby.pl
run_eruby.pl, no_write=0, wiki=0, xhtml=0
sh: 1: fruby: not found
died on ch01/ch01.rbtex, 32512, cmd=BOOK_OUTPUT_FORMAT='print' DIR='ch01' fruby ch01/ch01temp.postm4 >ch01/ch01temp.tex at scripts/run_eruby.pl line 147.
make: *** [Makefile:26: default] Error 127

**Comment by bcrowell** [comment]
Same issue, same answer.

**Comment by bcrowell** [comment]
The issue may be because you don't have "." in your path. I've updated the scripts to try to make this so it won't be a problem.

**Comment by RobinHankin** [comment]
thanks for that, it seemed to fix the `fruby` problem but:

```
general_relativity-master % make
perl -Iscripts scripts/run_eruby.pl
run_eruby.pl, no_write=0, wiki=0, xhtml=0
eruby_util.rb: figure ordered-geometry not found in ch01/figs or [nil, nil, nil], ch=01
section title stack = Ordered geometry
most recent begin_sec successfully processed was for Ordered geometry
died on ch01/ch01.rbtex, 65280, cmd=BOOK_OUTPUT_FORMAT='print' DIR='ch01' ./fruby ch01/ch01temp.postm4 >ch01/ch01temp.tex at scripts/run_eruby.pl line 147.
make: *** [default] Error 20
general_relativity-master % 
```

**Comment by igiann** [comment]
Thanks a lot it worked for me, now I can read your book!

**Comment by bcrowell** [comment]
@igiann : You don't need to compile the book from source in order to read it. Just download the pdf: http://www.lightandmatter.com/genrel/

**Comment by bcrowell** [comment]
@RobinHankin : Read the README file, which tells you how to create the figures.

**Comment by RobinHankin** [comment]
success!  Thank you!  That was my bad: `make all_figures` did report an error (caused by an infelicity in the inkscape setup) but I didn't see it and incorrectly assumed that it had worked.  All good now, cheers.
