### ISSUE TITLE
File INTERNALS is missing

### ISSUE THREAD

**Issue by valera-rozuvan** [bcrowell/general_relativity#2]
This repository mentions the file `INTERNALS` in 2 places:

- file [README](https://github.com/bcrowell/general_relativity/blob/master/README#L47) line 47
- file [scripts/eruby_util.rb](https://github.com/bcrowell/general_relativity/blob/master/scripts/eruby_util.rb#L15) line 15

Has this file accidentally been removed from git source? If so, can it be added back please?

**Comment by bcrowell** [comment]
Thanks for pointing this out. I've edited the README to point to a URL that contains this documentation.
